bind 0.0.0.0
protected-mode no
port 26379
dir /tmp
sentinel monitor hmdp-master 172.30.0.10 6379 2
sentinel auth-pass hmdp-master 123456
sentinel down-after-milliseconds hmdp-master 3000
sentinel failover-timeout hmdp-master 10000
sentinel parallel-syncs hmdp-master 1
